### ISSUE TITLE
run second_start_ovpnsocks failed

### ISSUE THREAD

**Issue by ohyeah521** [limitfan/ShadowOVPN#1]
[root@ ShadowOVPN]#  docker run -d \
>     --rm \
>     --device=/dev/net/tun \
>     --name=ovpnsocks \
>     --cap-add=NET_ADMIN \
>     --publish 127.0.0.1:1081:1080 \
>     --volume "$(pwd)/ovpn/:/etc/openvpn/:ro" \
>     leenwu/ovpnsocks
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by limitfan** [comment]
This indicates that your Docker is not running as normal. You need to start the Docker daemon service to run this command.
Commands as following should be used to restart and check Docker service:
```
$ sudo service docker restart
$ sudo service docker status (should see active (running))
```

**Comment by ohyeah521** [comment]
@limitfan  it's worked. thanks.
